version: '3.3'

services:
  api:
    build:
      context: api
    image: ramshorn_api
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "URL_PREFIX=api/"
    depends_on:
      - postgres
    volumes:
      - ./api/src/ramshorn_api:/src/src/ramshorn_api

  frontend:
    build:
      context: frontend
    image: ramshorn_frontend
    volumes:
      - ./frontend/src:/src/src

  proxy:
    image: nginx
    depends_on:
      - frontend
      - api
    volumes:
      - ./docker/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:8014:8014

  postgres:
    image: postgres:9.6
